In [11]:
import numpy as np


In [87]:
a=np.random.randint(2,10,50)
a

array([3, 3, 6, 6, 4, 9, 8, 3, 7, 6, 4, 5, 9, 2, 6, 9, 6, 5, 4, 4, 3, 9,
       5, 5, 2, 7, 6, 8, 7, 9, 2, 7, 5, 7, 3, 5, 7, 8, 8, 8, 4, 6, 2, 4,
       7, 8, 7, 7, 7, 7])

In [81]:
a.shape


(50,)

In [91]:
b=np.random.randint(23,67,(8,9))
b

array([[36, 23, 29, 30, 52, 24, 54, 62, 52],
       [44, 36, 61, 45, 61, 25, 32, 31, 50],
       [54, 32, 23, 28, 50, 23, 42, 26, 39],
       [31, 54, 33, 62, 57, 46, 23, 45, 64],
       [24, 38, 28, 64, 55, 61, 42, 27, 25],
       [65, 36, 60, 25, 31, 52, 66, 46, 50],
       [39, 64, 31, 31, 26, 61, 43, 43, 65],
       [62, 26, 41, 43, 25, 50, 29, 26, 28]])

In [93]:
b.shape

(8, 9)

In [97]:
b[1:5]

array([[44, 36, 61, 45, 61, 25, 32, 31, 50],
       [54, 32, 23, 28, 50, 23, 42, 26, 39],
       [31, 54, 33, 62, 57, 46, 23, 45, 64],
       [24, 38, 28, 64, 55, 61, 42, 27, 25]])

In [103]:
import pandas as pd

In [119]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [117]:
np.array(k)

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [121]:
t=pd.Series(k)

0      [4, 7]
1      [2, 9]
2      [7, 3]
3    [90, 50]
dtype: object

In [127]:
pd.DataFrame(t)

NameError: name 't' is not defined

In [ ]:
import pandas as pd
import seaborn as sns

In [1]:
sns.get_dataset_names()


NameError: name 'sns' is not defined